[env:native]
platform = native
platform_packages = platformio/toolchain-gccmingw32@^1.0.0
extra_scripts = pre:use_mingw.py
test_framework = unity
test_build_src = yes
build_flags = -I test/mocks -std=c++14 -static-libgcc -static-libstdc++
